version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./src
    ports:
      - "8501:8501"
    command: streamlit run streamlit_main.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./src:/app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app