[server]
enableXsrfProtection = false
enableCORS = false
baseUrlPath=""

[browser]
serverAddress="acareerai.com"

[client]
showSidebarNavigation = false

[theme]
primaryColor="#ff8247"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f1fdff"
textColor="#2d2e29"
font="serif"
base="light"