[server]
enableXsrfProtection = false
enableCORS = false
baseUrlPath=""

[browser]
serverAddress="acareerai.com"

[client]
showSidebarNavigation = false
showErrorDetails = false

[theme]
primaryColor="#ff9747"
backgroundColor="#ffffff"
secondaryBackgroundColor="#ffffff"
textColor="#2d2e29"
font="serif"
base="light"


[global]

# By default, Streamlit displays a warning when a user sets both a widget
# default value in the function defining the widget and a widget value via
# the widget's key in `st.session_state`.
# If you'd like to turn off this warning, set this to True.
# Default: false
disableWidgetStateDuplicationWarning = false

# If True, will show a warning when you run a Streamlit-enabled script
# via "python my_script.py".
# Default: true
showWarningOnDirectExecution = false