[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = false

[theme]
primaryColor="#906db2"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#498a6a"
font="serif"
base="light"