[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = false

[theme]
primaryColor="#768d87"
backgroundColor="#ffffff"
secondaryBackgroundColor="#e6f7f8"
textColor="#2d2e29"
font="serif"
base="light"