[server]
enableXsrfProtection = false
enableCORS = false
baseUrlPath="app"

[browser]
serverAddress="acareerai.com"

[client]
showSidebarNavigation = false

[theme]
primaryColor="#FF6347"
backgroundColor="#ffffff"
secondaryBackgroundColor="#ffffff"
textColor="#2d2e29"
font="serif"
base="light"