[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = false

[theme]
primaryColor="purple"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="serif"
base="light"