[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = false

[theme]
primaryColor="#FF6347"
backgroundColor="#ffffff"
secondaryBackgroundColor="#ffffff"
textColor="#2d2e29"
font="serif"
base="light"