[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = false

[theme]
primaryColor="#c88b3e"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#e6f7f8"
textColor="#0d0e0es"
font="serif"
base="light"